### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by spomajom** [LorenzCK/OnTopReplica#111]
i can open the program but the window no longer shows on the dektop. 
it shows up on the bar at the bottom and i can hover over it but it is no longer showing as a usable window on the dektop.
any help would be great

**Comment by LorenzCK** [comment]
Hello @spomajom,
under the program's settings directory:
`C:\Users\<your username>\AppData\Local\Lorenz_Cuno_Klopfenstein`
you'll find a number of "OnTopReplica" directories. Try deleting every single directory in order to fully reset OnTopReplica and let it start from scratch. That should fix the issue.

**Comment by spomajom** [comment]
bingo! fixed. thank you
