### ISSUE TITLE
can not see the live video

### ISSUE THREAD

**Issue by jianboy** [LorenzCK/OnTopReplica#135]
OS system: windows 10

browser: Microsoft Edge  Version 105.0.1343.53 (Official build) (64-bit)

OnTopReplica: v3.5.1-fix

![image](https://user-images.githubusercontent.com/11532015/193183749-7b31cde9-1c5a-4bae-a77e-3d8a35a42059.png)

**Comment by DarkIrata** [comment]
Does it work when you focus the Browser? Under Chrome there is a setting which causes that.

**Comment by jianboy** [comment]
Yes, it works well. **but it stopped when the Edge browser window is minimize.**

**Comment by jianboy** [comment]
you can see this video:

https://user-images.githubusercontent.com/11532015/193782452-a43e442e-5096-4727-ac19-3750f1a5d914.mp4

**Comment by DarkIrata** [comment]
I don't know if it will fix it for minimizing, but to make it work when running in the beackground you have to change the WindowOcclusionEnabled flag to false.
chrome://flags/#calculate-native-win-occlusion
edge://flags/#calculate-native-win-occlusion

I had it to set via registry for chrome after version 99+, i don't know if it is still neccessery.
[HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome] 
"WindowOcclusionEnabled"=dword:00000000

Not sure what the edge path would be. But since edge is based on chromium, it shouldn't be that different.

**Comment by jianboy** [comment]
But any other window, what should I do? for example:

https://user-images.githubusercontent.com/11532015/193788263-d839ff8f-d719-4126-8be6-c8a40b8985ff.mp4

**Comment by jianboy** [comment]
**thank you very much!**
