### ISSUE TITLE
Feature Request: Opacity/transparency mask

### ISSUE THREAD

**Issue by BobTheHunted** [LorenzCK/OnTopReplica#146]
Using this program is quite helpful, but the opacity settings are lacking.  Specifically, I think it needs the ability to use a black and white image as a transparency mask, so only part of the OTR window is transparent, rather than the entire thing at once.  I'm not requesting real-time chroma key or color removal type of functionality, but a basic "cut out" overlay.

For example, an image with a white square in the middle would make that white area transparent on the OTR window, but the black area in the background of the image would be fully opaque.  Maybe an automatic way to split the window into several smaller windows to form that shape would work better than rendering changes

**Comment by LorenzCK** [comment]
Hi @BobTheHunted,
unfortunately the project has been on hold for several years and I think it won't be updated soon. While I fully understand your feature request and think it would be very helpful, because of how OnTopReplica is implemented at the moment, it is technically impossible to do and would require a full rewrite of how windows are “cloned”. 😢
