### ISSUE TITLE
Option to Scale the Window Axis Independently

### ISSUE THREAD

**Issue by cheatfreak47** [LorenzCK/OnTopReplica#27]
This would be useful for example, Youtube videos that have been stretched, you could use it to unstretch them to 4:3 from 16:9.

You would probably implement this by adding a checkbox in settings saying "Maintain Aspect Ratio" which would be enabled by default.

When unticked, users can scale the window X and Y independent of one another with the video being scaled horizontally or vertically in accordance with the stretch.

**Comment by LorenzCK** [comment]
Hi @cheatfreak47,
I understand the use-case, but unfortunately this cannot be implemented because the thumbnail “clones” are handled by Windows itself, using its “[DWM thumbnails](https://msdn.microsoft.com/en-us/library/windows/desktop/aa969541(v=vs.85).aspx)” feature. This means that OnTopReplica does not have any control over how the thumbnails are drawn to screen and it cannot transform or *stretch* them in any way. Sorry. 😞
