### ISSUE TITLE
Enable rotation of the main frame

### ISSUE THREAD

**Issue by MPSOS1** [LorenzCK/OnTopReplica#56]
It would be useful to be able to rotate main frame. In case of overlapping with images for comparison purpose, rotation is something highly desired. 
By the way. Great app!

**Comment by LorenzCK** [comment]
Thanks @MPSOS1, glad you like the app! 😊 
Mirroring, rotation, etc. have been suggested previously (see #18) and they would definitely be very useful, but because of the way OnTopReplica clones target windows, these features are technically not possible to implement. It *might* be possible in the future by radically changing how OnTopReplica works (see #48).
