### ISSUE TITLE
Add Flip, Rotate and Deform

### ISSUE THREAD

**Issue by ZafotheNinja** [LorenzCK/OnTopReplica#57]
I am comparing several graphs to find similarities and the ability to flip the replicated window over the vertical or horizontal axis would be really helpful. 

I also think it would be neat to be able to rotate the replicated window along its center point x number of degrees. 

Ability to deform the window non-linearly?

Any/all of these possible? It seems like they would be easy to implement.

**Comment by LorenzCK** [comment]
Hi @ZafotheNinja,
yours is a very interesting use-case for OnTopReplica. The rotation/deformation/flipping/etc. feature request has been submitted by several other users and I personally would like to implement it: unfortunately, because of how OnTopReplica's window cloning is implemented, it is technically not possible to modify the cloned windows in any way (they are replicated directly by Windows and the program has no access to the graphical data).

It *might* be possible in the future (see also issue #56), but it would require very profound changes to the program to which I cannot currently commit to (since I can't even find time to fix bugs 😞). I will update you here if this should change in the future.
