### ISSUE TITLE
OnTopReplica in Linux

### ISSUE THREAD

**Issue by williamjosh** [LorenzCK/OnTopReplica#66]
Sad that OnTopReplica isn't available for Linux. Can anyone do it?

**Comment by LorenzCK** [comment]
As mentioned in the issue about a MacOS version, a direct port of OnTopReplica is probably impossible to make, since OTR relies heavily on the how the DWM works on Windows. Similar programs for MacOS exist however ([Fenetre](https://fenêt.re/) and [PiP](https://github.com/amitv87/PiP)), which could be an interesting starting point for anyone wanting to work on something similar for Linux. 😊

**Comment by williamjosh** [comment]
Thanks for your response. After some researches, I've found one similar to onTopReplica for linux users. It's a gnome shell extension called [Window Corner Preview](https://github.com/medenagan/window-corner-preview).

**Comment by LorenzCK** [comment]
Great, glad to hear that. 👍
