### ISSUE TITLE
The "live" feed in the clone window stops as soon as i minimize  a windows or alt tab from a fullscreen program.

### ISSUE THREAD

**Issue by OneSlize** [LorenzCK/OnTopReplica#74]
So the thing is you say you can monitor with this in the FAQ but for example if i clone a Chrome tab that is playing a video and then minimize that source (Chrome tab) it stops playing in the AlwaysOnTopReplica cloned window. That might be fully intended and i'm just dumb and have misunderstood how to use it properly. 

But i thought i should ask.

**Comment by nagado** [comment]
Same issue, happens intermittenly

**Comment by LorenzCK** [comment]
Unfortunately, this is intended (or rather, unavoidable) behavior: OnTopReplica makes use of the built-in DWM Thumbnails of Windows, which is the same feature that shows window thumbnails on the Windows Taskbar. For efficiency, Windows stops refreshing windows once they are invisible or minimized.

The only “solution” is to simply move the cloned window off-screen or hide it behind other windows, instead of minimizing it.

Future versions of OnTopReplica _may_ try to add a mode that “cloaks” the cloned window at some point: this should effectively hide the window from sights while keeping the thumbnail updated.

**Comment by OneSlize** [comment]
Okay gotcha.
