### ISSUE TITLE
Just a couple questions

### ISSUE THREAD

**Issue by SimonPDX** [LorenzCK/OnTopReplica#80]
Want to use this for games that won't maximize to 4K, ones with scaling issues or poor performance when ran native, but I'm curious:

Is there latency in the replica? Compression (or other degradation of image quality)? FPS cap?

Thanks so much, been using this for years.

**Comment by LorenzCK** [comment]
Hi @SimonPDX,
OnTopReplica uses the [built-in mechanisms of Windows' own DWM Manager](https://docs.microsoft.com/en-us/windows/desktop/dwm/thumbnail-ovw). There is no latency since the final image is composited at the same time the original window is displayed on screen. Also, no compression and no FPS cap: the program doesn't transfer and copy any memory in fact.
On one hand this means that this is the most lightweight option available, but it also has its limitations: OnTopReplica has no control over whether the image is actually cloned or not (cloning is disabled for minimized windows, for instance) and scaling uses the in-built process (bilinear, I guess).

Glad you find the program useful. Cheers!

**Comment by SimonPDX** [comment]
@LorenzCK

Thank you so much for the same day reply! That's all great news too, with that info it really does seem like an amazing option for me to play 1080p games, then using the 2:1 scaling option, and locking it to the top corner on my 4K display, the scaling is really crisp. Love it!
